/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 floorTwo.gltf 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
// import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
// import {useLoader} from "@react-three/fiber";

const Model = (props) => {
    // const gltf = useLoader(GLTFLoader, "./ThreeD/floorTwo.gltf");
  const { nodes, materials } = useGLTF('./ThreeD/floorTwo.gltf');
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Body_1.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_2.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_3.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_4.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_5.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_6.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_7.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_8.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_9.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_10.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_11.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_12.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_13.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_14.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_15.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_16.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_17.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_18.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_19.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_20.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_21.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_22.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_23.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_24.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_25.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_26.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_27.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_28.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_29.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_30.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_31.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_32.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_33.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_34.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_35.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_36.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_37.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_38.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_39.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_40.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_41.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_42.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_43.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_44.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_45.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_46.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_47.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_48.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_49.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_50.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_51.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_52.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_53.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_54.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_55.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_56.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_57.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_58.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_59.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_60.geometry} material={materials.Mtl} />
        <mesh geometry={nodes.Body_61.geometry} material={materials.Mtl} />
      </group>
    </group>
  );
};

export default Model;

useGLTF.preload('./ThreeD/floorTwo.gltf');
