#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
yarn run lint:fix
#yarn run lint:pre-commit # Not sure if needed, if issues arise, uncomment and delete the line above

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
